package Testing_and_Old_Stuff;

import java.time.LocalDate;

public class todo {

    private int id;             // a unique ID number, generated by the system
    private String title;       // a title of 3-20 characters
    private enum Priority {low, medium, high}   // dunno if enum works here
    private String description; // a description of 0-255 characters
    private LocalDate dueDate;  // dunno if LocalDate works here.. p.11 on slide








    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }
}
